name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install Dependencies
        run: |
          cd docs
          npm install
      
      - name: Build
        run: |
          cd docs
          npm run build
        env:
          PUBLIC_URL: /SquidNorm
      
      - name: Copy Markdown Files
        run: |
          mkdir -p docs/build/languages
          cp languages/*.md docs/build/languages/
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs/build