<!-- filepath: c:\Users\cesai\Documents\codeProjects\SquidNorm\.github\workflows\gh-pages.yml -->
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Convert Markdown files to HTML
        run: |
          npm install -g marked
          mkdir -p _site/languages
          cp index.html _site/
          for file in languages/*.md; do
            filename=$(basename "$file" .md)
            marked -i "$file" -o "_site/languages/${filename}.html"
          done

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: _site