name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

# Autoriser le workflow à créer et pousser vers la branche gh-pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          # Désactiver la mise en cache pour éviter les erreurs
      
      - name: Install Dependencies
        run: |
          cd docs
          npm install
      
      - name: Build
        run: |
          cd docs
          npm run build
        env:
          PUBLIC_URL: /SquidNorm
      
      - name: Copy Markdown Files
        run: |
          mkdir -p docs/build/languages
          cp -r languages/*.md docs/build/languages/
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build
          # La branche est gh-pages par défaut dans la v4